site_name: Streamdaq Docs
repo_url: https://github.com/bilpapster/stream-DaQ
repo_name: datalab/streamdaq
theme:
  logo: images/logo.png
  favicon: images/logo.png
  name: material
  features:
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  font:
    text: Nunito
    code: JetBrains Mono
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://datalab.csd.auth.gr/
plugins:
  - search
  - git-committers:
      repository: Datalab-Csd-Auth/streamdaq
      branch: main
      enabled: true
  - glightbox
  - mkdocs-jupyter:
      execute: true
      allow_errors: false
      kernel_name: python3
      include_source: True
  - git-revision-date-localized:
      enable_creation_date: false
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tilde
nav:
  - Home: index.md
  - Plug-and-play Examples:
    - notebooks/starting_example.ipynb
