site_name: Streamdaq v2 Docs
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Tutorials: notebooks/starting_example.ipynb
